AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBUsername:
    Description: The username for the database
    Type: String
  DBPassword:
    Description: The password for the database
    Type: String
    NoEcho: true
  AMI:
    Description: The AMI to use for the EC2 instance
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs

Resources:
  SSMForEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: t2.micro
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y amazon-linux-extras
          amazon-linux-extras install postgresql13
          export DB_USERNAME=${DBUsername}
          export DB_PASSWORD=${DBPassword}
          echo "DB_USERNAME=${DBUsername}" > /tmp/db_credentials
          echo "DB_PASSWORD=${DBPassword}" >> /tmp/db_credentials
      Tags:
      - Key: Name
        Value: AWS-EC2-Example-Exporting-Parameters

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMForEC2Role

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
    Description: The ID of the EC2 instance
  EC2PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: The public IP of the EC2 instance
